dist: trusty
jobs:
  include:
    - stage: test
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # - docker build -t esp32-sdk:latest .
      # - docker tag esp32-sdk:latest $DOCKER_USERNAME/esp32-sdk:latest
    - stage: push
      script:  
      - echo "foo"
      # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # - docker build -t esp32-sdk:latest .
      # - docker tag esp32-sdk:latest $DOCKER_USERNAME/esp32-sdk:latest
      # - docker push $DOCKER_USERNAME/esp32-sdk:latest
      # - docker push $DOCKER_USERNAME/esp32-sdk:$TRAVIS_TAG
stages:
  - test
  - name: push
    if: (branch = master)
  